### ISSUE TITLE
Cannot define variables with "var"

### ISSUE THREAD

**Issue by itslenny** [maxogden/node-repl#2]
I've noticed that if I run a file using node-repl and define a variable using var to define it I do not have access to that variable, but without var I do.

Example:

```
> var a="hello";
undefined
> a
ReferenceError: a is not defined
    at REPLServer.eval (eval at <anonymous> (/Users/Lenny/Desktop/tdd_oop/oop/house2.js:32:27), <anonymous>:1:1)
    at REPLServer.repl.start.eval (/Users/Lenny/Desktop/tdd_oop/oop/house2.js:32:22)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
>
```

**VS**

```
> a="hello"
'hello'
> a
'hello'
>
```

**Comment by max-mapper** [comment]
published fix as 1.0.5. thanks for reporting
