### ISSUE TITLE
Fix #3 breaks simple case

### ISSUE THREAD

**Issue by pborenstein** [maxogden/node-repl#4]
Looks like #3 broke the simple case:

```
$ node --version
v0.12.0
$ npm ls -g node-repl
/usr/local/lib
└── node-repl@1.0.5

$ cat foo.js
var pizza = 11;

$ node-repl foo.js
> pizza
ReferenceError: pizza is not defined
    at eval (eval at <anonymous> (/Users/philip/work/foo.js:12:27), <anonymous>:1:1)
    at Object.eval (native)
    at REPLServer.repl.start.eval (/Users/philip/work/foo.js:12:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
> ^D
```

Roll back to previous version:

```
$ npm uninstall -g node-repl
unbuild node-repl@1.0.5

$ npm install -g node-repl@1.0.4
/usr/local/bin/node-repl -> /usr/local/lib/node_modules/node-repl/bin.js
node-repl@1.0.4 /usr/local/lib/node_modules/node-repl
└── strip-bom@1.0.0 (first-chunk-stream@1.0.0, is-utf8@0.2.0)

$ node-repl foo.js
> pizza
11
> foo = 10
10
> var fie = 10
undefined
> fie
ReferenceError: fie is not defined
    at REPLServer.eval (eval at <anonymous> (/Users/philip/work/foo.js:13:27), <anonymous>:1:1)
    at REPLServer.repl.start.eval (/Users/philip/work/foo.js:13:22)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
>

```

**Comment by mafintosh** [comment]
Should be fixed in 2.0.0 now but my fix only supports node >= 0.12 and iojs as it uses a generator.
