### ISSUE TITLE
Not working on node 0.12

### ISSUE THREAD

**Issue by nicola** [maxogden/node-repl#6]
This library is amazing.

However, I see you used:

```
  var NODE_REPL_LOOP = (function * () {
                                 ^
```

And i get this error:

```
/Users/mozilla/Proj/schemas/index.js:46
  var NODE_REPL_LOOP = (function * () {
                                 ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.require.extensions..js (/usr/local/lib/node_modules/node-repl/bin.js:19:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-repl/bin.js:22:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

Maybe you want to specify some flags to use / node version?

**Comment by max-mapper** [comment]
OOPS. It looks like node 0.12 doesn't have a new enough v8 to have --harmony enabled by default. I though it did, sorry. I'll try and figure out a fix!

**Comment by ackalker** [comment]
As a workaround, if you're using a *nixish environment, you can create a simple wrapper script or alias.

Shell script (be sure to name it something _other_ than node-repl!):

``` sh
#!/bin/sh
exec node --harmony $(which node-repl) "$@"
```

(Bash) alias:

``` sh
$ alias node-repl='node --harmony $(which node-repl)'
```

Ideally, this should be handled by a js wrapper script for bin.js. I don't know of any way that doesn't involve ugly messing with child_process.spawn and having two Node processes running for each REPL. I guess that means using a plain ol' batch file on Windows.

**Comment by ackalker** [comment]
The pull request above suffers from the "running two node processes" problem, but it can easily be reverted as soon as ES6 stuff becomes default.
Tested with Node 0.12.7, but should work with any version supporting ES6.

**Comment by crobinson42** [comment]
This could probably be closed considering node 0.12 isn't supported anymore?
