### ISSUE TITLE
Not working at Windows OS

### ISSUE THREAD

**Issue by tooto1985** [maxogden/node-repl#9]
SyntaxError: Unexpected token }
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.require.extensions..js (C:\Users\Tommy\AppData\Roaming\nvm\v4.2.3\
node_modules\node-repl\bin.js:19:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Tommy\AppData\Roaming\nvm\v4.2.3\node_module
s\node-repl\bin.js:22:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by crobinson42** [comment]
@tooto1985 is this still an issue?

**Comment by tooto1985** [comment]
The 2.0.2 version is resolved this bug. Thank you.
